---

- name: Create a MUNGE Key
  block:
    - name: Define munge_keygen_script.
      set_fact:
        munge_keygen_script: >-
          {{ (munge_version_major | int >= 0 and
             munge_version_minor | int >= 5 and
             munge_version_patch | int >= 14) |
             ternary(__munge_kgs_new, __munge_kgs_old) }}
      when: munge_keygen_script is not defined

    - name: Create new key.
      command: '{{ munge_keygen_script }}'
      args:
        creates: '{{ munge_key_file }}'
      register: _munge_key_created
  run_once: yes
  delegate_to: '{{ munge_key_host }}'

- name: Synchronize key with {{ munge_key_host }}.
  synchronize:
    src: '{{ munge_key_file }}'
    dest: '{{ munge_key_file }}'
    mode: push
    checksum: '{{ synchronize_checksum }}'
    archive: '{{ synchronize_archive }}'
  delegate_to: '{{ munge_key_host }}'
  notify: restart munge
  when: >-
    not ansible_check_mode or
    not _munge_key_created.changed | bool

- name: Check if {{ munge_key_file }} exists.
  stat:
    path: '{{ munge_key_file }}'
  register: _munge_key_stat

- name: Make sure the key has the correct permissions.
  file:
    path: '{{ munge_key_file }}'
    owner: '{{ __munge_user_name }}'
    group: '{{ __munge_group_name }}'
    mode: 0400
  when: >-
    not ansible_check_mode or
    _munge_key_stat.stat.exists | bool

...
