---

- ansible.builtin.import_tasks: variables.yml

- ansible.builtin.import_tasks: user.yml
  when: munge_user_create | bool

- ansible.builtin.include_tasks: 'setup-{{ ansible_os_family }}.yml'
- ansible.builtin.import_tasks: version.yml
- ansible.builtin.import_tasks: configure.yml
- ansible.builtin.import_tasks: service.yml

...
